/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp_restaurante_model.gui_menu.opciones;

import java.awt.BorderLayout;
import myapp_restaurante_model.gui_menu.Menu;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCCliente;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCComentarios;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCEmpleado;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCMesa;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCProducto;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCReserva;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCTipoProducto;
import myapp_restaurante_model.gui_menu.opciones.consultas.PCUsuarios;

public class Opciones_Consultas extends javax.swing.JPanel {

    Menu menu;

    /**
     * Creates new form NewJPanel
     *
     * @param menu
     */
    public Opciones_Consultas(Menu menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cUsuario = new javax.swing.JLabel();
        cReservas = new javax.swing.JLabel();
        cTProductos = new javax.swing.JLabel();
        cComentarios = new javax.swing.JLabel();
        cEmpleado = new javax.swing.JLabel();
        cClientes = new javax.swing.JLabel();
        cProducto = new javax.swing.JLabel();
        cMesa = new javax.swing.JLabel();
        cPedido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(810, 540));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(cUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        cReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cReservasMouseClicked(evt);
            }
        });
        jPanel1.add(cReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, 200));

        cTProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cTProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cTProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cTProductosMouseClicked(evt);
            }
        });
        jPanel1.add(cTProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 200));

        cComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cComentariosMouseClicked(evt);
            }
        });
        jPanel1.add(cComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        cEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseClicked(evt);
            }
        });
        jPanel1.add(cEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        cClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cClientesMouseClicked(evt);
            }
        });
        jPanel1.add(cClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        cProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cProductoMouseClicked(evt);
            }
        });
        jPanel1.add(cProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, 200));

        cMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMesaMouseClicked(evt);
            }
        });
        jPanel1.add(cMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 200));

        cPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 200));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 42)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Usuarios");
        jLabel6.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clientes");
        jLabel7.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo de");
        jLabel8.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 60));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Producto");
        jLabel9.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 410, -1, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reservas");
        jLabel10.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 170, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 42)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Empleado");
        jLabel11.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 255, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Comentarios");
        jLabel16.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 180, 40));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Mesa");
        jLabel13.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_mantenimiento_usuarios/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 200, 660, 140));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Productos");
        jLabel12.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 60));

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Pedidos");
        jLabel15.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 170, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void cClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cClientesMouseClicked
        // TODO add your handling code here:
        PCCliente ppc;
        ppc = new PCCliente();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();

    }//GEN-LAST:event_cClientesMouseClicked

    private void cComentariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cComentariosMouseClicked
        // TODO add your handling code here:
        PCComentarios ppc;
        ppc = new PCComentarios();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cComentariosMouseClicked

    private void cMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMesaMouseClicked
        // TODO add your handling code here:
        PCMesa ppc;
        ppc = new PCMesa();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cMesaMouseClicked

    private void cEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseClicked
        // TODO add your handling code here:
        PCEmpleado ppc;
        ppc = new PCEmpleado();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cEmpleadoMouseClicked

    private void cProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cProductoMouseClicked
        // TODO add your handling code here:
        PCProducto ppc;
        ppc = new PCProducto();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cProductoMouseClicked

    private void cReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cReservasMouseClicked
        // TODO add your handling code here:
        PCReserva ppc;
        ppc = new PCReserva();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cReservasMouseClicked

    private void cTProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cTProductosMouseClicked
        // TODO add your handling code here:
        PCTipoProducto ppc;
        ppc = new PCTipoProducto();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cTProductosMouseClicked

    private void cUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cUsuarioMouseClicked
        // TODO add your handling code here:
        PCUsuarios ppc;
        ppc = new PCUsuarios();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cClientes;
    private javax.swing.JLabel cComentarios;
    private javax.swing.JLabel cEmpleado;
    private javax.swing.JLabel cMesa;
    private javax.swing.JLabel cPedido;
    private javax.swing.JLabel cProducto;
    private javax.swing.JLabel cReservas;
    private javax.swing.JLabel cTProductos;
    private javax.swing.JLabel cUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
