/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp_restaurante_model.gui_menu.opciones;

import java.awt.BorderLayout;
import myapp_restaurante_model.gui_menu.Menu;
import myapp_restaurante_model.gui_menu.opciones.movimientos.PMAESProducto;
import myapp_restaurante_model.gui_menu.opciones.procesos.PPCancelarReserva;
import myapp_restaurante_model.gui_menu.opciones.procesos.PPCobroPedido;
import myapp_restaurante_model.gui_menu.opciones.procesos.PPDistribución;

public class Opciones_Procesos extends javax.swing.JPanel {

    Menu menu;

    /**
     * Creates new form NewJPanel
     *
     * @param menu
     */
    public Opciones_Procesos(Menu menu) {
        this.menu = menu;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cES = new javax.swing.JLabel();
        cPedidos = new javax.swing.JLabel();
        cCancelarPedidos = new javax.swing.JLabel();
        cActualizarESProducto = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(810, 540));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cESMouseClicked(evt);
            }
        });
        jPanel1.add(cES, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        cPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cPedidosMouseClicked(evt);
            }
        });
        jPanel1.add(cPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        cCancelarPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cCancelarPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cCancelarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cCancelarPedidosMouseClicked(evt);
            }
        });
        jPanel1.add(cCancelarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        cActualizarESProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/circulo.gif"))); // NOI18N
        cActualizarESProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cActualizarESProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cActualizarESProductoMouseClicked(evt);
            }
        });
        jPanel1.add(cActualizarESProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jLabel.setBackground(new java.awt.Color(0, 0, 0));
        jLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 30)); // NOI18N
        jLabel.setForeground(new java.awt.Color(102, 255, 153));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Cobro Pedido");
        jLabel.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dis Propina");
        jLabel2.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 180, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cancelar Reservas");
        jLabel3.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 333, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_mantenimiento_usuarios/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 200, 660, 140));

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Actualiza E.S");
        jLabel4.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 333, 180, 50));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Producto");
        jLabel5.setToolTipText("Nombre o dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 343, 180, 80));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void cESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cESMouseClicked
        // TODO  your handling code here:Cobro pedido
        PPCobroPedido ppc;
        ppc = new PPCobroPedido();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();

    }//GEN-LAST:event_cESMouseClicked

    private void cCancelarPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCancelarPedidosMouseClicked
        // TODO add your handling code here: reservas
        PPCancelarReserva ppc;
        ppc = new PPCancelarReserva();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();

    }//GEN-LAST:event_cCancelarPedidosMouseClicked

    private void cActualizarESProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cActualizarESProductoMouseClicked
        // TODO add your handling code here:
        PMAESProducto ppc;
        ppc = new PMAESProducto();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cActualizarESProductoMouseClicked

    private void cPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cPedidosMouseClicked
        // TODO add your handling code here:
        PPDistribución ppc;
        ppc = new PPDistribución();
        menu.getjPanel_Menu().removeAll();
        ppc.setSize(810, 540);
        ppc.setLocation(0, 0);
        menu.getjPanel_Menu().add(ppc, BorderLayout.CENTER);
        menu.getjPanel_Menu().revalidate();
        menu.getjPanel_Menu().repaint();
    }//GEN-LAST:event_cPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cActualizarESProducto;
    private javax.swing.JLabel cCancelarPedidos;
    private javax.swing.JLabel cES;
    private javax.swing.JLabel cPedidos;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
