/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp_restaurante_model.gui_menu.opciones.procesos;

import java.awt.Font;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;
import myapp_restaurante_model.bussiness.GeneradorPDF;

import myapp_restaurante_model.domain.Pedido;
import myapp_restaurante_model.gui_menu.JFGuardar;
import myapp_restaurante_model.gui_menu.TextPrompt;
import myapp_restaurante_model.gui_menu.table_custom.TableActionCellEditor;
import myapp_restaurante_model.gui_menu.table_custom.TableActionCellRender;
import myapp_restaurante_model.gui_menu.table_custom.TableActionEvent;
import myapp_restaurante_model.logic.FilesTxt;
import myapp_restaurante_model.logic.LogicFilesTxt;

 
public final class PPCobroPedido extends javax.swing.JPanel {
    
    private GeneradorPDF gpdf;
    private TextPrompt t;
    private final JFGuardar pg;
    private final String[] eti;
    private String result;
    private Pedido p;
    private final LogicFilesTxt lTxt;
    private final FilesTxt f;
    private int size;
    String addressTxt;
    private Object[][] OTableInformation;

    /**
     * Creates new form NewJPanel
     */
    public PPCobroPedido() {

        //jframe de guardar *es un efecto
        this.pg = new JFGuardar();

        //etiquetas de la tabla
        String[] etiquetas = {"ID", "Fecha", "ID Cliente", "Valor", "Valor itbis", "Propina", "Concepto", "Status", "ID Camarero", "Id Mesa", "Accion"};
        this.eti = etiquetas;

        //se inicializa todo el codigo del jframe
        initComponents();
        //edita los jtexfields
        setTextPront();

        ////////////////
        result = "";
        //iniciliciamos las logicas
        lTxt = new LogicFilesTxt();
        f = new FilesTxt();
        //Direcion del txt
        addressTxt = "src\\myapp_restaurante_model\\data\\pedido.txt";
        //Se obtiene el tamaño del txt
        size = lTxt.getInformation(f.readFile(addressTxt)).length;
        
        result = f.readFile(addressTxt);

        //Se obtiene el contenido del txt
        OTableInformation = lTxt.getObject(f.readFile(addressTxt));

        //edita las tablas para autollenarse//Primero se mete el tamaño que se obtuvo segun el txt y luego la informacion
        if (result.isEmpty()) {
            result = ""; //si estya vacio no crea nada nuevo ni guarda nada

        } else {
            result = lTxt.getObjetsConverString(OTableInformation);
            //  JOptionPane.showConfirmDialog(null, result);
            editarTabla(OTableInformation);
        }

        //No va editar nada
        TableActionEvent event;
        event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                }
                System.out.println("Edit row : " + row);
            }
            
            @Override
            public void onDelete(int row) {
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                }
                System.out.println("Delete row : " + row);
            }
            
            @Override
            public void onView(int row) {
                System.out.println("View row : " + row);
            }
        };
        
        table.getColumnModel().getColumn(table.getColumnModel().getColumnCount() - 1).setCellRenderer(new TableActionCellRender());
        table.getColumnModel().getColumn(table.getColumnModel().getColumnCount() - 1).setCellEditor(new TableActionCellEditor(event));
        //volvemos a editar la tabla para acomodar los parametros de acuerdo a los margenes que se necesita
        table.setIntercellSpacing(new java.awt.Dimension(5, 1));
        table.setRowHeight(40);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(table.getColumnModel().getColumnCount() - 1).setPreferredWidth(130);
        }
        
        jButtonPdf.setEnabled(false);
        
    }

    //tabla para editar
    public void editarTabla(Object[][] data) {
        
        table.setModel(new javax.swing.table.DefaultTableModel(
                data, eti
        ));
        jScrollPane1.setViewportView(table);
    }
    
    private void setTextPront() {
        t = new TextPrompt("ID", jTextCodigo);
        t.changeAlpha(0.75f);
        t.changeStyle(Font.ITALIC);
        t.changeFontSize(11);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButtonPdf = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextPagar = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 153));
        jLabel4.setText("ID");
        jLabel4.setToolTipText("Nombre o dirección");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        jTextCodigo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCodigo.setCaretColor(new java.awt.Color(51, 0, 51));
        jTextCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextCodigoMouseClicked(evt);
            }
        });
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });
        add(jTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "IdCliente", "Valor ", "Itbis", "Propina", "Pedido", "IdCamarero", "Mesa", "Accion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setIntercellSpacing(new java.awt.Dimension(5, 1));
        table.setRowHeight(40);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 42, 570, 490));

        jButtonPdf.setBackground(new java.awt.Color(102, 255, 153));
        jButtonPdf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonPdf.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPdf.setText("Generar");
        jButtonPdf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPdfMouseClicked(evt);
            }
        });
        jButtonPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPdfActionPerformed(evt);
            }
        });
        add(jButtonPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 120, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 153));
        jLabel7.setText("Borrar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 20));

        jBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(102, 255, 153));
        jBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/consultas.png"))); // NOI18N
        jBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscarMouseClicked(evt);
            }
        });
        add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 153));
        jLabel5.setText("Valor a Pagar");
        jLabel5.setToolTipText("Nombre o dirección");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        jTextPagar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPagar.setCaretColor(new java.awt.Color(51, 0, 51));
        jTextPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPagarMouseClicked(evt);
            }
        });
        jTextPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPagarActionPerformed(evt);
            }
        });
        add(jTextPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/gradient (2).gif"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 830, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextCodigoMouseClicked
        // TODO add your handling code here:ID

        // Agregar FocusListener
        jTextCodigo.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // No se necesita hacer nada cuando se gana el enfoque
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                // Mostrar mensaje cuando se pierde el enfoque

            }
            
        });
        

    }//GEN-LAST:event_jTextCodigoMouseClicked
//Consructor


    private void jButtonPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPdfMouseClicked
        // TODO add your handling code here:pdf
        String idCliente = lTxt.getInformationIndividual(lTxt.getInformattionById(result, jTextCodigo.getText()))[2];
        if (jTextCodigo.getText().isEmpty() && lTxt.isId(result, idCliente)) {
            JOptionPane.showMessageDialog(null, "Coloca correctamente los datos");
        } else {
            action();
        }

    }//GEN-LAST:event_jButtonPdfMouseClicked
    public void action() {
        double valorPagar = Double.parseDouble(jTextPagar.getText());
        //obtengo los datos del pedido

        String fecha = lTxt.getInformationIndividual(lTxt.getInformattionById(result, jTextCodigo.getText()))[1];
        
        String valor = lTxt.getInformationIndividual(lTxt.getInformattionById(result, jTextCodigo.getText()))[3];
        String valoritbis = lTxt.getInformationIndividual(lTxt.getInformattionById(result, jTextCodigo.getText()))[4];
        String valorpropina = lTxt.getInformationIndividual(lTxt.getInformattionById(result, jTextCodigo.getText()))[5];
        
        double subtotal = Double.parseDouble(valor) + Double.parseDouble(valorpropina);
        double vitbis = Double.parseDouble(valoritbis);
        double total = subtotal + vitbis;
        //condicion para que la suma de dinero a pagar sea mayor
        if (total < Integer.parseInt(jTextPagar.getText())) {
            //genera el pdf
            gpdf = new GeneradorPDF();
            gpdf.createPDF(GeneradorPDF.generarFactura(jTextCodigo.getText(), fecha, subtotal, vitbis, total, valorPagar));
            
            try {
                //Ponemos a "Dormir" el programa durante los ms que queremos
                Thread.sleep(5 * 100);
                lTxt.getPdf("src\\myapp_restaurante_model\\pdf\\Pedido.pdf");
            } catch (Exception e) {
                System.out.println(e);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "La suma a pagar es inferior");
            
        }
    }
    private void jButtonPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPdfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPdfActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here://Borrar
        jTextCodigo.setText("");
        jTextCodigo.setEnabled(true);
        jTextPagar.setText("");
        //  jTextArea1.setText("");

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscarMouseClicked
        // TODO add your handling code here:Buscar
        // JOptionPane.showMessageDialog(null, "result"+result);
        if (lTxt.isId(result, jTextCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "Existe");
            //obtendo el los datos segun la posicion 

            jTextCodigo.setEnabled(false);

            //jTextArea1.setText(comentario);
        }
        jButtonPdf.setEnabled(true);
    }//GEN-LAST:event_jBuscarMouseClicked

    private void jTextPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPagarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPagarMouseClicked

    private void jTextPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jBuscar;
    private javax.swing.JButton jButtonPdf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextPagar;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
