/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp_restaurante_model.gui_menu;

import myapp_restaurante_model.gui_menu.opciones.Opciones_Movimientos;
import myapp_restaurante_model.gui_menu.opciones.Opciones_Procesos;
import myapp_restaurante_model.gui_menu.opciones.Opciones_Consultas;
import myapp_restaurante_model.gui_menu.opciones.Opciones_Mantenimiento;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import myapp_restaurante_model.bussiness.Controller_Gui_Mantenimiento_Usuarios;

 
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
    }

    public Menu(boolean check, String user) {
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
        if (!check) {
            lMantenimiento.setVisible(false);
        }
        jlUser.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlabelDerechos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lProcesos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lMantenimiento = new javax.swing.JLabel();
        lMovimientos = new javax.swing.JLabel();
        lConsultas = new javax.swing.JLabel();
        jlUser = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelDerechos.setBackground(new java.awt.Color(255, 255, 255));
        jlabelDerechos.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jlabelDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jlabelDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 30));

        jLabel2.setBackground(new java.awt.Color(0, 204, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Online");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        lProcesos.setBackground(new java.awt.Color(255, 255, 255));
        lProcesos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/procesos.png"))); // NOI18N
        lProcesos.setText(" Procesos");
        lProcesos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lProcesosMouseClicked(evt);
            }
        });
        jPanel2.add(lProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 30));

        jPanel5.setBackground(new java.awt.Color(0, 255, 0));
        jPanel5.setForeground(new java.awt.Color(153, 0, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel5.setText("Resta");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel6.setText("Urante");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        lMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        lMantenimiento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/mantenimiento.png"))); // NOI18N
        lMantenimiento.setText(" Mantenimiento");
        lMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMantenimientoMouseClicked(evt);
            }
        });
        jPanel2.add(lMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 30));

        lMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        lMovimientos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/movimientos.png"))); // NOI18N
        lMovimientos.setText(" Momivientos");
        lMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMovimientosMouseClicked(evt);
            }
        });
        jPanel2.add(lMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 30));

        lConsultas.setBackground(new java.awt.Color(255, 255, 255));
        lConsultas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/consultas.png"))); // NOI18N
        lConsultas.setText("Consultas");
        lConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultasMouseClicked(evt);
            }
        });
        jPanel2.add(lConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 40));

        jlUser.setBackground(new java.awt.Color(255, 255, 255));
        jlUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/usuario (1).png"))); // NOI18N
        jlUser.setText("User");
        jPanel2.add(jlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/salir.png"))); // NOI18N
        jLabel10.setText(" Salir");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 190, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, 230));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapp_restaurante_model/gui_menu/iconos/cambiar_usuario.png"))); // NOI18N
        jLabel4.setText("Cambiar Usuario");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 12, -1, 36));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 810, 60));

        jPanel_Menu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        jPanel_Menu.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 810, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void lProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProcesosMouseClicked
        // TODO add your handling code here:

        Opciones_Procesos oP = new Opciones_Procesos(this);
        jPanel_Menu.removeAll();
        oP.setSize(810, 540);
        oP.setLocation(0, 0);
        jPanel_Menu.add(oP, BorderLayout.CENTER);
        jPanel_Menu.revalidate();
        jPanel_Menu.repaint();

    }//GEN-LAST:event_lProcesosMouseClicked
    private void derechos() {
// Obtener año actual
        int anioActual = java.time.Year.now().getValue();

        // Mensaje de derechos reservados
        String mensajePieDeAplicacion = "© " + anioActual + " Todos los derechos reservados.";
        jlabelDerechos.setText(mensajePieDeAplicacion);
    }
    private void lMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMantenimientoMouseClicked
        // TODO add your handling code here: Mantenimiento
        Opciones_Mantenimiento oMa;
        oMa = new Opciones_Mantenimiento(this);
        jPanel_Menu.removeAll();
        oMa.setSize(810, 540);
        oMa.setLocation(0, 0);
        jPanel_Menu.add(oMa, BorderLayout.CENTER);
        jPanel_Menu.revalidate();
        jPanel_Menu.repaint();
    }//GEN-LAST:event_lMantenimientoMouseClicked

    private void lMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMovimientosMouseClicked
        // TODO add your handling code here:Movimientos
        Opciones_Movimientos oM = new Opciones_Movimientos(this);
        jPanel_Menu.removeAll();
        oM.setSize(810, 540);
        oM.setLocation(0, 0);
        jPanel_Menu.add(oM, BorderLayout.CENTER);
        jPanel_Menu.revalidate();
        jPanel_Menu.repaint();
    }//GEN-LAST:event_lMovimientosMouseClicked

    private void lConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultasMouseClicked
        // TODO add your handling code here:consultas
        Opciones_Consultas oC = new Opciones_Consultas(this);
        jPanel_Menu.removeAll();
        oC.setSize(810, 540);
        oC.setLocation(0, 0);
        jPanel_Menu.add(oC, BorderLayout.CENTER);
        jPanel_Menu.revalidate();
        jPanel_Menu.repaint();
    }//GEN-LAST:event_lConsultasMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Controller_Gui_Mantenimiento_Usuarios cg = new Controller_Gui_Mantenimiento_Usuarios();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JLabel jlUser;
    private javax.swing.JLabel jlabelDerechos;
    private javax.swing.JLabel lConsultas;
    private javax.swing.JLabel lMantenimiento;
    private javax.swing.JLabel lMovimientos;
    private javax.swing.JLabel lProcesos;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return jlabelDerechos;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jlabelDerechos = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return lProcesos;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.lProcesos = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return lMantenimiento;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.lMantenimiento = jLabel8;
    }

    public JLabel getjLabel9() {
        return lMovimientos;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.lMovimientos = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel_Menu() {
        return jPanel_Menu;
    }

    public void setjPanel_Menu(JPanel jPanel4) {
        this.jPanel_Menu = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }


}
